import type { EventId, IncidentId, TaskId, UserId } from '@/types';
export const PATHS = {
    landing: '/',
    login: '/login',
    register: '/register',
    auth: '/auth',
    home: '/events',
    eventsList: '/events',
    eventDetail: (id: EventId | string | number = ':eventId'): string => `/events/${id}`,
    eventDashboard: (id: EventId | string | number = ':eventId'): string => `/events/${id}/dashboard`,
    eventMap: (id: EventId | string | number = ':eventId'): string => `/events/${id}/map`,
    eventIncidents: (id: EventId | string | number = ':eventId'): string => `/events/${id}/incidents`,
    eventTasks: (id: EventId | string | number = ':eventId'): string => `/events/${id}/tasks`,
    taskDetail: (eventId: EventId | string | number = ':eventId', taskId: TaskId | string | number = ':taskId'): string => `/events/${eventId}/tasks/${taskId}`,
    taskMatching: (eventId: EventId | string | number = ':eventId', taskId: TaskId | string | number = ':taskId'): string => `/events/${eventId}/tasks/${taskId}/matching`,
    taskBookings: (eventId: EventId | string | number = ':eventId', taskId: TaskId | string | number = ':taskId'): string => `/events/${eventId}/tasks/${taskId}/bookings`,
    incidentDetail: (id: IncidentId | string | number = ':incidentId'): string => `/incidents/${id}`,
    resources: '/resources',
    usersDirectory: '/users',
    userDetail: (id: UserId | string | number = ':userId'): string => `/users/${id}`,
    userProfileEdit: (id: UserId | string | number = ':userId'): string => `/users/${id}/edit`,
    skills: '/skills',
    myTasks: '/me/tasks',
    profile: '/me',
    notifications: '/notifications',
    forbidden: '/403',
    notFound: '*',
} as const;
